[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "soundly"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "PyQt6>=6.4.0",
    "numpy>=1.20.0",
]

[tool.maturin]
features = ["pyo3/extension-module"]